CREATE DATABASE gestion_recetas;
USE gestion_recetas;

-- TABLA AUTOR--
CREATE TABLE IF NOT EXISTS author (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(255),
    biography TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

--TABLA COCINA/ESTILOS--
CREATE TABLE IF NOT EXISTS cuisines (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(80) NOT NULL UNIQUE,
    description VARCHAR(255) NULL,
    county_origin VARCHAR(80) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

--TABLA INGREDIENTES--
CREATE TABLE IF NOT EXISTS ingredients (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(120) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

--TABLA RECETAS--
CREATE TABLE IF NOT EXISTS recipes (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    author_id INT UNSIGNED NULL,
    cuisine_id INT UNSIGNED NULL,
    title VARCHAR(160) NOT NULL,
    description TEXT NULL,
    preparation LONGTEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_recipes_author FOREIGN KEY (author_id) REFERENCES author(id) ON DELETE SET NULL,
    CONSTRAINT fk_recipes_cuisine FOREIGN KEY (cuisine_id) REFERENCES cuisines(id) ON DELETE SET NULL
) ENGINE=InnoDB;

--TABLA PIVOTE ->  RECETAS_INGREDINTES--
CREATE TABLE IF NOT EXISTS recipe_ingredients (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    recipe_id INT UNSIGNED NOT NULL,
    ingredient_id INT UNSIGNED NOT NULL,
    quantity DECIMAL(10,3) NULL,
    unit VARCHAR(32) NULL,
    notes VARCHAR(150) NULL,

    CONSTRAINT fk_ri_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_ri_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON DELETE RESTRICT,
    UNIQUE KEY uq_recipe_ing (recipe_id, ingredient_id)
) ENGINE=InnoDB;